name: Create and Publish Docker image # Name of the workflow

on:
  push:
    branches: [main] # Workflow to run only when changes are made to `main` branch

env:
  REGISTRY: ghcr.io # Image registry, ghcr.io incase of GitHub Container Registry
  IMAGE_NAME: sammurphydev/ingress-cloudflare-tunnel-dns-provisioner # Name of the image comes from the repository name

jobs:
  release:
    runs-on: ubuntu-latest # GitHub Runner OS

    steps:
      - name: Checkout source code # Checksout the repository in the GitHub runner
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}

      - name: Node Dependencies
        run: yarn install --frozen-lockfile

      - name: Automated Version Bump # This action step reads and updates the version number acc to commit message
        id: version-bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn release
          echo "::set-output name=TAG::$(cat package.json | jq -r .version)"

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }} # Uses the env defined above
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest, ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version-bump.outputs.TAG }}
          # Pushed the image with `latest` tag and the new semantic version obtained from the version-bump step
